# Generated by Django 4.1.5 on 2023-01-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=20)),
                ('c', models.FloatField()),
                ('d', models.FloatField()),
                ('e', models.FloatField()),
                ('f', models.FloatField()),
                ('g', models.FloatField()),
                ('h', models.FloatField()),
                ('i', models.FloatField()),
                ('j', models.FloatField()),
                ('k', models.FloatField()),
                ('l', models.FloatField()),
                ('m', models.FloatField()),
                ('n', models.FloatField()),
                ('o', models.FloatField()),
                ('p', models.FloatField()),
                ('q', models.FloatField()),
                ('r', models.FloatField()),
                ('s', models.FloatField()),
                ('t', models.FloatField()),
                ('u', models.CharField(max_length=20)),
            ],
        ),
    ]
