# Generated by Django 4.1.5 on 2023-01-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_predresult_b_alter_predresult_u'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.FloatField()),
                ('f', models.FloatField()),
                ('l', models.FloatField()),
                ('o', models.FloatField()),
                ('s', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.FloatField()),
                ('q', models.FloatField()),
                ('r', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.FloatField()),
                ('h', models.FloatField()),
                ('k', models.FloatField()),
                ('m', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.FloatField()),
                ('d', models.FloatField()),
                ('e', models.FloatField()),
                ('j', models.FloatField()),
                ('n', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('u', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='PredResult',
        ),
    ]
