# Generated by Django 4.1.5 on 2023-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_economic_health_immunization_mortality_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='u',
            field=models.CharField(max_length=255),
        ),
    ]
